
services:
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception

  wordpress:
    environment:
      ENABLE_REDIS: "true"
    depends_on:
      - redis

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      FTP_USER: ${FTP_USER}
      FTP_HOST: ${FTP_HOST}
      FTP_PASSWORD_FILE: /run/secrets/ftp_password
    volumes:
      - wordpress-volume:/home/${FTP_USER}/wordpress
    networks:
      - inception
    secrets:
    - ftp_password

  static:
    build: ./requirements/bonus/static
    container_name: static
    restart: always
    ports:
      - "666:666"
    volumes:
      - static-volume:/var/www/html
    networks:
      - inception
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

volumes:
  static-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER:-vdurand}/data/static

secrets:
  ftp_password:
    file: ${SECRET_DIR:-../secrets}/ftp_password.txt